stream_over_http_enabled: true
server:
  http_listen_port: 3200
  grpc_listen_port: 3205

  log_level: info


distributor:
  receivers:
    otlp:
      protocols:
        http:
          #TODO: Expose ports
        grpc:
          endpoint: 0.0.0.0:3208
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    zipkin:
    

# From example, will need adjusting.
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

#querier:
#  frontend_worker:
#    frontend_address: tempo:3205


metrics_generator:
  registry:
    external_labels:
      source: tempo
      collection_interval: 5s
  storage:
    path: /var/tempo/wal
    remote_write:
#      TODO: Change to alloy remote write
      - url: ${ALLOY_PROM_REMOTE:-httpL//nginx-gateway.svc.cluster.local:9090/api/v1/push}
        send_exemplars: true
        send_native_histograms: true
  processor:
    service_graphs:
      dimensions:
        - http.method
        - http.target
        - http.status_code
    span_metrics:
      dimensions:
        - http.method
        - http.target
        - http.status_code
        - service.name
        - span.name
        - span.kind
        - status.code



ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 4h       # May need to be kept for longer

storage:
  trace:
    backend: s3
    wal:
      path: /var/tempo/wal
#    Yep, not insecure at all
    s3:
      bucket: tempo-data
      endpoint: ${TEMPO_S3_ENDPOINT:-minio.minio-store.svc:443}
      access_key: ${TEMPO_S3_ACCESS_KEY:-bucket}
      secret_key: ${TEMPO_S3_SECRET_KEY:-supersecret}
      insecure: ${TEMPO_S3_INSECURE:-false}
      tls_insecure_skip_verify: true

overrides:
  defaults:
    metrics_generator:
      processors: [ 'span-metrics', 'service-graphs']

usage_report:
  reporting_enabled: false

