---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus.io/service-monitor: "false"
  name: mimir-member-list
spec:
  clusterIP: None
  ports:
    - port: 7946
      appProtocol: tcp
      targetPort: 7946
      protocol: TCP
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/part-of: memberlist