---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: galah-logging
spec:
  endpoints:
  - interval: 15a
    port: http-metrics
    relabelings:
    - action: replace
      replacement: galah-monitoring/loki
      sourceLabels:
      - job
      targetLabel: job
    scheme: http
  namespaceSelector:
      matchNames:
      - galah-logging
  selector:
    matchExpressions:
    - key: prometheus.io/service-monitor
      operator: NotIn
      values:
      - "false"
    matchLabels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki