apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galah-logging
helmCharts:
  - name: loki
    version: 6.10.0
    repo: https://grafana.github.io/helm-charts
    releaseName: helm-loki
    namespace: galah-logging
    includeCRDs: false
    valuesFile: values.yaml

resources:
  - namespace.yaml
