apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galah-monitoring
helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 0.8.1
    releaseName: alloy
    namespace: galah-monitoring
    includeCRDs: false
    valuesFile: values.yaml

resources:
  - namespace.yaml


configMapGenerator:
  - name: alloy-config
    namespace: galah-monitoring
    files:
      - configs/config.alloy

  - name: alloy-modules-kubernetes-metrics
    namespace: galah-monitoring
    files:
    - configs/alloy-modules/kubernetes/metrics/annotations.alloy
    - configs/alloy-modules/kubernetes/metrics/podmonitors.alloy
    - configs/alloy-modules/kubernetes/metrics/servicemonitors.alloy
    - configs/alloy-modules/kubernetes/metrics/integrations-scrape.alloy


  - name: alloy-modules-kubernetes-logs
    namespace: galah-monitoring
    files:
    - configs/alloy-modules/kubernetes/logs/json-remove-nulls.alloy
    - configs/alloy-modules/kubernetes/logs/keep-labels.alloy
    - configs/alloy-modules/kubernetes/logs/kubernetes-cluster-events.alloy
    - configs/alloy-modules/kubernetes/logs/kubernetes-default-level.alloy
    - configs/alloy-modules/kubernetes/logs/log-levels.alloy
    - configs/alloy-modules/kubernetes/logs/log-sampling.alloy
    - configs/alloy-modules/kubernetes/logs/pods.alloy
    - configs/alloy-modules/kubernetes/logs/relabel-with-level.alloy
    - configs/alloy-modules/kubernetes/logs/structured-metadata.alloy

  - name: alloy-modules-kubernetes-traces
    namespace: galah-monitoring

  - name: alloy-modules-kubernetes-jobs
    namespace: galah-monitoring
    files:
    - configs/alloy-modules/kubernetes/jobs/receive-otlp-telemetry.alloy
    - configs/alloy-modules/kubernetes/jobs/receive-k6.alloy
    - configs/alloy-modules/kubernetes/jobs/kubernetes-scrape.alloy
    - configs/alloy-modules/kubernetes/jobs/testbed-scrape.alloy

  - name: alloy-modules-integrations
    namespace: galah-monitoring
    files:
    - configs/alloy-modules/kubernetes/integrations/alloy.alloy
    - configs/alloy-modules/kubernetes/integrations/discovery.alloy
    - configs/alloy-modules/kubernetes/integrations/loki.alloy
    - configs/alloy-modules/kubernetes/integrations/mimir.alloy
    - configs/alloy-modules/kubernetes/integrations/scrape.alloy
    - configs/alloy-modules/kubernetes/integrations/tempo.alloy

  - name: alloy-modules-integrations-kubernetes
    namespace: galah-monitoring
    files:
    - configs/alloy-modules/kubernetes/integrations/kubernetes/api-server.alloy
    - configs/alloy-modules/kubernetes/integrations/kubernetes/kube-resources.alloy
    - configs/alloy-modules/kubernetes/integrations/kubernetes/kube-state-metrics.alloy
    - configs/alloy-modules/kubernetes/integrations/kubernetes/kubelet.alloy
    - configs/alloy-modules/kubernetes/integrations/kubernetes/probes.alloy

  - name: alloy-modules-kubernetes-collectors
    namespace: galah-monitoring
    files:
    - configs/alloy-modules/kubernetes/collectors/jaeger/jaeger-collector.alloy
    - configs/alloy-modules/kubernetes/collectors/loki/loki-collector.alloy
    - configs/alloy-modules/kubernetes/collectors/otlp/otlp-collector.alloy
    - configs/alloy-modules/kubernetes/collectors/prometheus/prometheus-collector.alloy
    - configs/alloy-modules/kubernetes/collectors/zipkin/zipkin-collector.alloy
    - configs/alloy-modules/kubernetes/collectors/k6/k6-collector.alloy


  - name: alloy-modules-kubernetes-provider
    namespace: galah-monitoring
    files:
      - configs/alloy-modules/provider/self_hosted.alloy