#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization
#namespace: galah-tracing
#helmCharts:
#  - name: tempo
#    namespace: galah-tracing
#    version: 1.10.3
#    repo: https://grafana.github.io/helm-charts
#    releaseName: tempo
#    includeCRDs: false
#    additionalValuesFiles:
#    - k3d-values.yaml
#
#
#resources:
#  - servicemonitor.yaml
#  - namespace.yaml
#  - service.yaml
#
#secretGenerator:
#  - name: tempo-env
#
##configMapGenerator:
##  - name: tempo-config
##    namespace: galah-tracing
##    files:
##      - configs/tempo.yaml
##
#generators:
#   - configmap-generator.yaml
##  - |-
##    apiVersion: builtin
##    kind: ConfigMapGenerator
##    metadata:
##      name: tempo
##      namespace: galah-tracing
##    behavior: replace
##    files:
##    - configs/tempo.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - service.yaml
  - statefulset.yaml
  - servicemonitor.yaml
  - namespace.yaml

generators:
  - configmap-generator.yaml