---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
#  name: galah
#  namespace: galah-tracing
spec:
  type: ClusterIP
  ports:
    - port: 3200
      name: http-metrics
      targetPort: 3200
    - port: 3205
      name: grpc
      appProtocol: grpc
      targetPort: 3205
  selector:
    app.kubernetes.io/name: tempo