apiVersion: 1

datasources:

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki
    url: http://nginx.gateway.svc.cluster.local.:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
#    orgId: 1

    url: http://nginx.gateway.svc.cluster.local.:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: tempo

  - name: Mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://nginx.gateway.svc.cluster.local.:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    timeInterval: '60s'
    uid: mimir
#    jsonData:
#      httpMethod: GET
