apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sts-certmanager-cert
  namespace: minio-store
spec:
  dnsNames:
    - sts
    - sts.minio-store
    - sts.minio-store.svc
    - sts.minio-store.svc.cluster.local
  secretName: sts-tls
  issuerRef:
    name: minio-store-issuer