---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-operator-ca-certificate
  namespace: minio-store
spec:
  isCA: true
  commonName: operator
  secretName: operator-ca-tls
  duration: 7018h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: minio-store-issuer
  namespace: minio-store
spec:
  ca:
    secretName: operator-ca-tls