---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: memberlist
  name: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: memberlist
  template:
    metadata:
      annotations:
        logs.grafana.com/scrape: "true"
      labels:
        app.kubernetes.io/part-of: memberlist
    spec:
      containers:
        - args:
            - -target=all,alertmanager
            - -config.file=/etc/mimir/configs/mimir.yaml
            - -config.expand-env=true
            - -alertmanager.enable-api=true
            - -memberlist.bind-addr=$(POD_IP)

          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: docker.io/grafana/mimir:2.13.0
          imagePullPolicy: IfNotPresent
          name: mimir
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 990m
              memory: 1Gi
          ports:
            - containerPort: 9090
              name: http-metrics
            - containerPort: 9095
              name: grpc-dist
            - containerPort: 7946
              name: http-memberlist
          readinessProbe:
            httpGet:
              port: http-metrics
              path: /ready
          volumeMounts:
            - mountPath: /etc/mimir/configs
              name: config
            - mountPath: /data
              name: storage
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: mimir-config
        - name: storage
          emptyDir:
            {}

