apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galah-tracing
helmCharts:
  - name: tempo
    version: 1.10.3
    repo: https://grafana.github.io/helm-charts
    releaseName: tempo
    namespace: galah-tracing
    includeCRDs: false
    valuesFile: values.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: tempo
        namespace: galah-tracing
      spec:
        template:
          spec:
            containers:
              - name: tempo
                ports:
                - name: grpc

                  containerPort: 3205
                  protocol: TCP
                - name: http-metrics
                  containerPort: 3200
                  protocol: TCP
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: tempo
        namespace: galah-tracing
      spec:
        ports:
          - name: grpc
            port: 3205
            targetPort: 3205
          - name: http-metrics
            port: 3200
            targetPort: 3200

resources:
  - namespace.yaml

secretGenerator:
  - name: tempo-env
    namespace: galah-tracing

#
#configMapGenerator:
#  - name: tempo-config
#    options:
#      disableNameSuffixHash: true
#    files:
#      - ../configs/tempo.yaml
