apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: operator
    repo: https://operator.min.io
    version: 6.0.2
    releaseName: operator
    namespace: minio-store
    includeCRDs: false
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - configs/cert-issuer.yaml
  - configs/cert.yaml