---
apiVersion: v1
kind: Service
metadata:
  name: chirp-server
  labels:
    app.kubernetes.io/name: chirp-server
spec:
  type: ClusterIP
  ports:
    - port: 7080
      name: http
      targetPort: http
      protocol: TCP
    - port: 80
      name: entry
      protocol: TCP
      targetPort: entry
  selector:
    app.kubernetes.io/name: chirp-server