
createConfigmap: false

envFromSecrets:
- name: grafana-env
  optional: true


ingress:
  enabled: true
  hosts:
  - grafana.localhost
  - localhost

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s

resources:
  requests:
    cpu: 100m
    memory: 250Mi
  limits:
    cpu: 250m
    memory: 512Mi

admin:
  existingSecret: "grafana-secret"
  userKey: admin-user
  password-key: admin-password

testFramework:
  enabled: false

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: 1
    folder: /dashboards
    searchNamespace: ALL
    folderAnnotation: grafana_dashboard_folder
    provider:
      name: sidecarProvider
      orgid: 1
      type: file
      disableDelete: false
      allowUiUpdates: false
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: 1
    searchNamespace: galah-monitoring
