apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: galah-monitoring

resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml
  - ingress.yaml


configMapGenerator:
  - name: grafana-config

    files:
      - custom.ini=configs/grafana.ini
  - name: grafana-dashboards
    files:
      - configs/definitions/k6-prometheus.json
  - name: grafana-datasources
    files:
      - configs/provisioning/datasources/datasources.yaml

secretGenerator:
  - name: grafana-env
    options:
      disableNameSuffixHash: true
    literals:
      - GF_FEATURE_TOGGLE_ENABLE=traceqlEditor tracesEmbeddedFlameGraph traceqlSearch correlations metricsSummary traceToMetrics datatrails
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
