apiVersion: v1
kind: Namespace
metadata:
  name: test-bed
---
apiVersion: v1
data:
  DEMO_SERVER_ENDPOINT: aHR0cDovL2NoaXJwLXNlcnZlcjo3MDgwL2hlbGxv
  OTEL_EXPORTER_OTLP_ENDPOINT: YWxsb3kuZ2FsYWgtbW9uaXRvcmluZy5zdmMuY2x1c3Rlci5sb2NhbDo0MzE3
kind: Secret
metadata:
  name: client-env
  namespace: test-bed
type: Opaque
---
apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: YWxsb3kuZ2FsYWgtbW9uaXRvcmluZy5zdmMuY2x1c3Rlci5sb2NhbDo0MzE3
kind: Secret
metadata:
  name: server-env-7428th2b97
  namespace: test-bed
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: chirp-client
  name: chirp-client
  namespace: test-bed
spec:
  ports:
  - port: 7090
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: chirp-client
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: chirp-server
  name: chirp-server
  namespace: test-bed
spec:
  ports:
  - name: http
    port: 7080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: chirp-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: chirp-client
  name: chirp-client
  namespace: test-bed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chirp-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chirp-client
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: client-env
        image: docker.io/maliciousbucket/chirp-client:master
        imagePullPolicy: IfNotPresent
        name: chirp-client
        ports:
        - containerPort: 7090
          name: http
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: chirp-server
  name: chirp-server
  namespace: test-bed
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chirp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chirp-server
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: server-env-7428th2b97
        image: docker.io/maliciousbucket/chirp-server:master
        imagePullPolicy: IfNotPresent
        name: chirp-server
        ports:
        - containerPort: 7080
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
