apiVersion: v1
data:
  config.env: |
    ZXhwb3J0IE1JTklPX0JST1dTRVI9Im9uIgpleHBvcnQgTUlOSU9fUk9PVF9QQVNTV09SRD
    0iYnVja2V0MTIzYWJjIgpleHBvcnQgTUlOSU9fUk9PVF9VU0VSPSJhZG1pbiIKZXhwb3J0
    IE1JTklPX1BST01FVEhFVVNfQVVUSF9UWVBFPSJwdWJsaWMiCmV4cG9ydCBNSU5JT19QUk
    9NRVRIRVVTX0pPQl9JRD0ibWluaW8tam9iIgo=
kind: Secret
metadata:
  labels:
    v1.min.io/tenant: galah
  name: minio-env
  namespace: minio-store
type: Opaque
---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YnVja2V0
  CONSOLE_SECRET_KEY: c3VwZXJzZWNyZXQ=
kind: Secret
metadata:
  labels:
    v1.min.io/tenant: galah
  name: minio-user
  namespace: minio-store
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-store-cert
  namespace: minio-store
spec:
  dnsNames:
  - minio
  - minio.minio-store
  - minio.minio-store.svc.cluster.local
  - '*.minio-store.svc.cluster.local'
  - '*.galah.minio-store.svc.cluster.local'
  issuerRef:
    name: minio-store-issuer
  secretName: galah-tls
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  labels:
    app: minio
  name: galah
  namespace: minio-store
spec:
  buckets:
  - name: mimir-blocks
  - name: mimir-ruler
  - name: mimir-alertmanager
  - name: loki-data
  - name: loki-ruler
  - name: tempo-data
  configuration:
    name: minio-env
  exposeServices:
    console: false
    minio: false
  externalCertSecret:
  - name: galah-tls
    type: cert-manager.io/v1
  features:
    bucketDNS: false
    enableSFTP: false
  image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - name: pool-15gb
    servers: 1
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
    volumesPerServer: 1
  prometheusOperator: false
  requestAutoCert: false
  subPath: /data
  users:
  - name: minio-user
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: minio-store
spec:
  endpoints:
  - path: /minio/v2/metrics/cluster
    port: https-minio
    relabelings:
    - replacement: minio-job
      sourceLabels:
      - job
      targetLabel: job
    - action: keep
      regex: .*-0$
      sourceLabels:
      - pod
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - path: /minio/v2/metrics/bucket
    port: https-minio
    relabelings:
    - replacement: minio-job-bucket
      sourceLabels:
      - job
      targetLabel: job
    - action: keep
      regex: minio
      sourceLabels:
      - service
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - path: /minio/v2/metrics/resource
    port: https-minio
    relabelings:
    - replacement: minio-job-resource
      sourceLabels:
      - job
      targetLabel: job
    - action: keep
      regex: minio
      sourceLabels:
      - service
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - minio-store
  selector:
    matchExpressions:
    - key: prometheus.io/service-monitor
      operator: NotIn
      values:
      - "false"
    - key: v1.min.io/tenant
      operator: Exists
