stream_over_http_enabled: true
server:
  http_listen_port: 3200
#  grpc_listen_port: 3205

  log_level: info


distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:
          endpoint: 0.0.0.0:3205
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    zipkin:
    

# From example, will need adjusting.
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s


metrics_generator:
  registry:
    external_labels:
      source: tempo
      collection_interval: 5s
  storage:
    path: /var/tempo/wal
    remote_write:
#      TODO: Change to alloy remote write
      - url: http://mimir:9090/api/v1/push
        send_exemplars: true
  traces_storage:
    path: /var/tempo/traces
  processor:
    service_graphs:
      dimensions:
        - http.method
        - http.target
        - http.status_code
    span_metrics:
      dimensions:
        - http.method
        - http.target
        - http.status_code
        - service.name
        - span.name
        - span.kind
        - status.code



ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 4h       # May need to be kept for longer

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      processors: ['local-blocks', 'span-metrics', 'service-graphs']

