---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirp-client
  labels:
    app.kubernetes.io/name: chirp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chirp-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chirp-client
    spec:
      containers:
        - name: chirp-client
          image: docker.io/maliciousbucket/chirp-client:master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7090
              name: http
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: client-env
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
