---
apiVersion: v1
kind: Service
metadata:
  name: chirp-client
  labels:
    app.kubernetes.io/name: chirp-client
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chirp-client
  ports:
    - port: 7090
      protocol: TCP
      targetPort: http