apiVersion: v1
kind: Namespace
metadata:
  name: galah-tracing
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: tempo
  name: tempo
  namespace: galah-tracing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempo-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempo-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempo-clusterrole
subjects:
- kind: ServiceAccount
  name: tempo
  namespace: galah-tracing
---
apiVersion: v1
data:
  config.yaml: "stream_over_http_enabled: true\nserver:\n  http_listen_port: 3200\n#
    \ grpc_listen_port: 3205\n\n  log_level: info\n\n\ndistributor:\n  receivers:\n
    \   otlp:\n      protocols:\n        http:\n        grpc:\n          endpoint:
    0.0.0.0:3205\n    jaeger:\n      protocols:\n        thrift_http:\n        grpc:\n
    \       thrift_binary:\n        thrift_compact:\n    zipkin:\n    \n\n# From example,
    will need adjusting.\nquery_frontend:\n  search:\n    duration_slo: 5s\n    throughput_bytes_slo:
    1.073741824e+09\n  trace_by_id:\n    duration_slo: 5s\n\n\nmetrics_generator:\n
    \ registry:\n    external_labels:\n      source: tempo\n      collection_interval:
    5s\n  storage:\n    path: /var/tempo/wal\n    remote_write:\n#      TODO: Change
    to alloy remote write\n      - url: http://mimir:9090/api/v1/push\n        send_exemplars:
    true\n  traces_storage:\n    path: /var/tempo/traces\n  processor:\n    service_graphs:\n
    \     dimensions:\n        - http.method\n        - http.target\n        - http.status_code\n
    \   span_metrics:\n      dimensions:\n        - http.method\n        - http.target\n
    \       - http.status_code\n        - service.name\n        - span.name\n        -
    span.kind\n        - status.code\n\n\n\ningester:\n  max_block_duration: 5m\n\ncompactor:\n
    \ compaction:\n    block_retention: 4h       # May need to be kept for longer\n\nstorage:\n
    \ trace:\n    backend: local\n    wal:\n      path: /var/tempo/wal\n    local:\n
    \     path: /var/tempo/blocks\n\noverrides:\n  defaults:\n    metrics_generator:\n
    \     processors: ['local-blocks', 'span-metrics', 'service-graphs']\n\n"
kind: ConfigMap
metadata:
  name: tempo
  namespace: galah-tracing
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-headless
spec:
  ports:
  - name: http-metrics
    port: 3200
  - appProtocol: grpc
    name: grpc
    port: 3205
    targetPort: 3205
  selector:
    app.kubernetes.io/name: tempo
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    prometheus.io/port: http-metrics
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: tempo
  name: tempo
  namespace: galah-tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  serviceName: tempo-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - -config.file=/conf/tempo.yaml
        - -config.expand-env=true
        - -target=all
        image: docker.io/grafana/tempo:2.5.0
        imagePullPolicy: IfNotPresent
        name: tempo
        ports:
        - containerPort: 3200
          name: http-metrics
        - containerPort: 3205
          name: grpc
        - containerPort: 55678
          name: opencensus
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/tempo/config
          name: config
        - mountPath: /var/tempo/wal
          name: storage
          subPath: wal
        - mountPath: /var/tempo/generator/wal
          name: storage
          subPath: generator
      serviceAccountName: tempo
      volumes:
      - emptyDir:
          sizeLimit: 10Gi
        name: storage
      - configMap:
          name: tempo
        name: config
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo
  namespace: galah-tracing
spec:
  endpoints:
  - interval: 15s
    port: http-metrics
    relabelings:
    - action: replace
      replacement: galah-tracing/tempo
      sourceLabels:
      - job
      targetLabel: job
    scheme: http
  namespaceSelector:
    matchNames:
    - galah-tracing
  selector:
    matchExpressions:
    - key: prometheus.io/service-monitor
      operator: NotIn
      values:
      - "false"
    matchLabels:
      app.kubernetes.io/instance: tempo
      app.kubernetes.op/name: tempo
